[private]
default:
    just --list

# Setup a bitcoin core source directory
setup source-dir:
    if [ ! -d "{{source-dir}}" ]; then echo "Error: Bitcoin Core source directory {{source-dir}} does not exist" exit 1; fi
    cp ./bitcoin/.envrc bitcoin/justfile {{source-dir}}

    echo ".envrc"  >> {{source-dir}}/.gitignore
    echo "justfile"  >> {{source-dir}}/.gitignore

    cd {{source-dir}} && direnv allow

